import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faUser, faLock, faSignOutAlt, faHome, faUsers, faBox,
  faChartBar, faChartLine, faChartArea, faCog, faBars, faTimes, faEye, faEyeSlash, faEdit,
  faTrash, faPlus, faSave, faSearch, faFilter, faDownload,
  faUpload, faFileExcel, faFilePdf, faCheck, faTimesCircle, faListUl,
  faExclamationTriangle, faInfoCircle, faArrowLeft,
  faArrowRight, faChevronDown, faChevronUp, faCalendar,
  faMoneyBillWave, faTruck, faClipboardList, faBoxes,
  faWarehouse, faHistory, faExchangeAlt, faTools,
  faWrench, faHardHat, faCalendarCheck, faFileInvoiceDollar,
  faShoppingCart, faFileAlt, faCalculator, faBolt, faRulerCombined,
  faMoneyCheckAlt, faHandHoldingUsd, faTags, faTag,
  faUndo, faCamera, faCopy, faImages, faImage, faBarcode, faQrcode,
  faTrashAlt, faBan, faArrowUp, faArrowDown, faSync,
  faFileContract, faSignature, faFileInvoice, faCoins, faFileImage,
  faWallet, faCreditCard, faUniversity, faUserTie,
  faBuilding, faMapMarkerAlt, faPhone, faEnvelope, faGlobe,
  faPalette, faComments, faShieldAlt, faKey,
  faUserCircle, faUmbrellaBeach, faPlusCircle, faFileSignature, faDatabase, faToolbox, faUserCog, faShoppingBag, faCartShopping,
  faTachometerAlt, faCalendarAlt, faDollarSign, faLandmark, faReceipt, faLaptop, faCubes, faCogs, faTrademark, faCar,
  faPrint, faPaperPlane, faEnvelopeOpen, faFunnelDollar, faChevronLeft, faChevronRight, faIdCard, faUsersCog,
  faHeadset, faChartPie, faTicketAlt, faBook,
  faClock, faClockRotateLeft, faCashRegister, faUserTimes, faHandshake, faHourglassHalf,
  faCalendarPlus, faCalendarDay, faUserPlus, faBell, faAddressBook, faSpinner, faDesktop,
  faCloudUploadAlt, faUnlink, faFileArchive, faPlug, faListOl, faFolderOpen, faTasks, faCheckCircle,
  faPen, faTrashCan,
  faBullseye, faBullhorn, faColumns, faTrophy, faInbox, faList, faBoxOpen,
  faBalanceScale, faTruckLoading, faMedal, faFileUpload, faUserCheck,
  faCrown, faShieldHalved, faBuildingShield, faMobileAlt, faQuestion,
  faBlog, faNewspaper, faShareAlt, faShareNodes, faMagic, faExternalLinkAlt, faGem, faCheckDouble,
  faThLarge, faQuestionCircle, faServer, faVideo, faUserLock,
  faWandMagicSparkles, faCircleInfo, faCircleCheck, faCircleExclamation, faTriangleExclamation,
  faAddressCard, faEnvelopeCircleCheck, faGlobeAmericas, faCircleDot, faSnowflake, faWind,
  faLightbulb, faStickyNote, faClipboardCheck, faAlignLeft, faLink,
  faHammer, faDroplet, faRocket, faMountain, faDraftingCompass, faChargingStation, faLayerGroup, faWater, faTrowel,
  faCircleXmark, faCirclePlus, faThermometerHalf, faBrush, faCertificate, faStar,
  faShoppingBasket, faMoon, faShieldVirus, faMicrochip, faPlayCircle, faPlay, faPhoneAlt, faSyncAlt, faFire, faLeaf,
  faBed, faTv, faStore, faAward, faFileCsv, faUserSecret, faFileLines, faPaperclip,
  faListCheck, faFileMedical, faGraduationCap, faHeart, faUsersSlash, faExclamationCircle, faSkullCrossbones
} from '@fortawesome/free-solid-svg-icons';

import { faWhatsapp, faFacebook, faFacebookF, faTwitter, faXTwitter, faCcVisa, faCcMastercard, faCcAmex, faCcPaypal } from '@fortawesome/free-brands-svg-icons';

library.add(
  faUser, faLock, faSignOutAlt, faHome, faUsers, faBox,
  faChartBar, faChartLine, faChartArea, faCog, faBars, faTimes, faEye, faEyeSlash, faEdit,
  faTrash, faPlus, faSave, faSearch, faFilter, faDownload,
  faUpload, faFileExcel, faFilePdf, faCheck, faTimesCircle, faListUl,
  faExclamationTriangle, faInfoCircle, faArrowLeft,
  faArrowRight, faChevronDown, faChevronUp, faCalendar,
  faMoneyBillWave, faTruck, faClipboardList, faBoxes,
  faWarehouse, faHistory, faExchangeAlt, faTools,
  faWrench, faHardHat, faCalendarCheck, faFileInvoiceDollar,
  faShoppingCart, faFileAlt, faCalculator, faBolt, faRulerCombined,
  faMoneyCheckAlt, faHandHoldingUsd, faTags, faTag,
  faUndo, faCamera, faCopy, faImages, faImage, faBarcode, faQrcode,
  faTrashAlt, faBan, faArrowUp, faArrowDown, faSync,
  faFileContract, faSignature, faFileInvoice, faCoins, faFileImage,
  faWallet, faCreditCard, faUniversity, faUserTie,
  faBuilding, faMapMarkerAlt, faPhone, faEnvelope, faGlobe,
  faPalette, faComments, faShieldAlt, faKey,
  faUserCircle, faUmbrellaBeach, faPlusCircle, faFileSignature, faDatabase, faToolbox, faUserCog, faShoppingBag, faCartShopping,
  faTachometerAlt, faCalendarAlt, faDollarSign, faLandmark, faReceipt, faLaptop, faCubes, faCogs, faTrademark, faCar,
  faPrint, faPaperPlane, faEnvelopeOpen, faFunnelDollar, faChevronLeft, faChevronRight, faIdCard, faUsersCog,
  faHeadset, faChartPie, faTicketAlt, faBook,
  faClock, faCashRegister, faUserTimes, faHandshake, faHourglassHalf,
  faCalendarPlus, faCalendarDay, faUserPlus, faBell, faAddressBook, faSpinner, faDesktop,
  faCloudUploadAlt, faUnlink, faFileArchive, faPlug, faListOl, faFolderOpen, faTasks, faCheckCircle,
  faPen, faTrashCan,
  faWhatsapp, faList, faBalanceScale, faTruckLoading, faMedal, faFileUpload, faUserCheck,
  faCrown, faShieldHalved, faBuildingShield, faMobileAlt, faQuestion,
  faBlog, faNewspaper, faShareAlt, faMagic, faExternalLinkAlt,
  faFacebook, faFacebookF, faTwitter, faXTwitter, faGem, faCheckDouble, faCcVisa, faCcMastercard, faCcAmex, faCcPaypal,
  faThLarge, faQuestionCircle, faServer, faVideo, faUserLock,
  faBullseye, faBullhorn, faColumns, faTrophy, faInbox, faBoxOpen,
  faWandMagicSparkles, faCircleInfo, faCircleCheck, faCircleExclamation, faTriangleExclamation,
  faAddressCard, faEnvelopeCircleCheck, faGlobeAmericas, faCircleDot, faSnowflake, faWind,
  faLightbulb, faStickyNote, faClipboardCheck, faAlignLeft, faLink,
  faHammer, faDroplet, faRocket, faMountain, faDraftingCompass, faChargingStation, faLayerGroup, faWater, faTrowel,
  faCircleXmark, faCirclePlus, faThermometerHalf, faBrush, faCertificate, faStar,
  faClockRotateLeft, faShoppingBasket, faMoon, faShieldVirus, faMicrochip, faPlayCircle, faPlay, faPhoneAlt, faSyncAlt, faFire, faLeaf,
  faBed, faTv, faStore, faAward, faFileCsv, faUserSecret, faFileLines, faPaperclip,
  faListCheck, faFileMedical, faGraduationCap, faHeart, faUsersSlash, faExclamationCircle, faSkullCrossbones
);

export { library };
