FROM nginx:alpine

# Copiar configuración
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

# Crear directorio y copiar assets públicos
WORKDIR /var/www/cdd_app
COPY public ./public

# Ajustar permisos (por si acaso)
RUN chmod -R 755 /var/www/cdd_app/public
